name: WhatTheBlock
author: Perri
version: 1.0.0
main: sk.perri.whattheblock.WhatTheBlockMain
commands:
    blockinfo:
        description: Get block info you are looking at or /blockinfo hand to get info aubout block in your hand
        usage: /blockinfo
permissions:
    whattheblock.*:
        description: All permissions from all commnads of WhatTheBlock plugin
        children:
            whattheblock.view: true
            whattheblock.hand: true
            whattheblock.cleardatabase: true
            whattheblock.history: true
        default: op
    whattheblock.view:
        description: Allows get info about block you looking at
        default: op
    whattheblock.hand:
        description: Allows get info about block you holding
        default: op
    whattheblock.cleardatabase:
        description: Allows to clear block history database
        default: op
    whattheblock.history:
        description: Allows to print history of the block
        default: op